// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    var enterReplies, leaveReplies;
    robot.hear(/octopus/i, function(res) {
      return res.send("Salut, salut!");
    });
    robot.respond(/open the (.*) doors/i, function(res) {
      var doorType;
      doorType = res.match[1];
      if (doorType === "pod bay") {
        return res.reply("I'm afraid I can't let you do that.");
      } else {
        return res.reply("Opening " + doorType + " doors");
      }
    });
    enterReplies = ['Hi', 'Target Acquired', 'Firing', 'Hello friend.', 'Gotcha', 'I see you'];
    leaveReplies = ['Are you still there?', 'Target lost', 'Searching'];
    robot.enter(function(res) {
      return res.send(res.random(enterReplies));
    });
    return robot.leave(function(res) {
      return res.send(res.random(leaveReplies));
    });
  };

}).call(this);

//# sourceMappingURL=example.js.map
