// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    return robot.respond(/open the (.*) doors/i, function(res) {
      var doorType;
      doorType = res.match[1];
      if (doorType === "pod bay") {
        res.send("I'm afraid I can't let you do that.");
        return res.send("https://www.youtube.com/watch?v=dSIKBliboIo");
      } else {
        return res.reply("Opening " + doorType + " doors");
      }
    });
  };

}).call(this);

//# sourceMappingURL=example.js.map
